### ISSUE TITLE
Failed to load gripper_left_controller

### ISSUE THREAD

**Issue by FawziLinggo** [KvalheimRacing/6DOF-Manipulator-Simulation#1]
Can't You Help me?

`[ERROR] [1653098644.323841101, 5.689000000]: Could not load controller 'gripper_right_controller' because controller type 'effort_controllers/JointEffortController' does not exist.
[ERROR] [1653098644.325410955, 5.689000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1653098645.327091, 6.429000]: Failed to load gripper_right_controller`

**Comment by KvalheimRacing** [comment]
Have you installed all available controllers? `sudo apt-get install ros*controller*`
If yes, then just do a google search for "ros controller type does not exist"
Unfortunatly I don't have time to help you more than that. Good luck

**Comment by s-a-tanjim** [comment]
In my case, ROS controller was missing. I just installed ros controller using ```sudo apt install ros-$ROS_DISTRO-ros-control ros-$ROS_DISTRO-ros-controllers``` and it worked.
